# Generated by Django 4.0 on 2023-10-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_ceateaccount_delete_react'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ceateaccount',
            new_name='Createaccount',
        ),
    ]
