# Generated by Django 4.0 on 2024-02-09 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_rename_ceateaccount_createaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('orderdate', models.DateField()),
                ('orderShipdate', models.DateField()),
                ('shipping_Addres', models.TextField()),
                ('customerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backapp.createaccount')),
            ],
        ),
    ]
