# Generated by Django 4.0 on 2024-02-09 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='emailid',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='password',
            field=models.TextField(max_length=16, validators=[django.core.validators.MinLengthValidator(8, 'the minimum character needed for the password')]),
        ),
    ]
