# Generated by Django 4.0 on 2024-05-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0005_alter_createaccount_emailid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
